NPK_MAGIC = 'NeoplePack_Bill'
NPK_FILENAME_DECORD_FLAG = bytes('puchikon@neople dungeon and fighter %s\x00' % ('DNF' * 73), encoding='ascii')

IMG_MAGIC_OLD = 'Neople Image File'
IMG_MAGIC = 'Neople Img File'

IMG_VERSION_1 = 1
IMG_VERSION_2 = 2
IMG_VERSION_4 = 4
IMG_VERSION_5 = 5
IMG_VERSION_6 = 6

IMAGE_FORMAT_1555 = 14
IMAGE_FORMAT_4444 = 15
IMAGE_FORMAT_8888 = 16
IMAGE_FORMAT_LINK = 17
IMAGE_FORMAT_DXT_1 = 18
IMAGE_FORMAT_DXT_3 = 19
IMAGE_FORMAT_DXT_5 = 20

IMAGE_FORMATS_RAW = (IMAGE_FORMAT_1555, IMAGE_FORMAT_4444, IMAGE_FORMAT_8888)
IMAGE_FORMATS_DDS = (IMAGE_FORMAT_DXT_1, IMAGE_FORMAT_DXT_3, IMAGE_FORMAT_DXT_5)
IMAGE_FORMATS_ALL = (IMAGE_FORMAT_LINK, *IMAGE_FORMATS_RAW, *IMAGE_FORMATS_DDS)

PIX_SIZE = {
    IMAGE_FORMAT_1555: 2,
    IMAGE_FORMAT_4444: 2,
    IMAGE_FORMAT_8888: 4,
    IMAGE_FORMAT_DXT_1: 2,
    IMAGE_FORMAT_DXT_3: 2,
    IMAGE_FORMAT_DXT_5: 4,
}

IMAGE_EXTRA_NONE = 5
IMAGE_EXTRA_ZLIB = 6
IMAGE_EXTRA_ZLIB_SPRITE = 7
